# This is a basic workflow to help you get started with Actions
name: Test, build and publish

# Controls when the action will run.
on:
  push:
    branches: ["**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Weekly build on Mondays at 8 am
  schedule:
    - cron: "0 8 * * 1"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # Directory that will be published on github pages
  PUBLISH_DIR: ./_build/html
  HDF5_MPI: "ON"
  HDF5_DIR: "/usr/local/"
  DISPLAY: ":99.0"
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-book:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/lab:v0.6.0-r1
   
    env:
      PYVISTA_TRAME_SERVER_PROXY_PREFIX: '/proxy/'
      PYVISTA_TRAME_SERVER_PROXY_ENABLED: "True"
      PYVISTA_OFF_SCREEN: false
      PYVISTA_JUPYTER_BACKEND: "panel"


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/checkout@v3
  
      # Upgrade setuptools and pip
      # https://github.com/pypa/setuptools/issues/3269#issuecomment-1254507377
      - name: Install apt dependencies and upgrade pip
        run: |
          apt-get update && apt-get install -y libgl1-mesa-glx libxrender1 xvfb
          python3 -m pip install -U "setuptools<=65.5.1" pip pkgconfig

      # Install `h5py`
      # https://github.com/hl5py/h5py/issues/2222
      - name: Install h5py and pip requirements
        run: |
          python3 -m pip install cython
          python3 -m pip install --no-build-isolation --no-binary=h5py h5py
          python3 -m pip install --no-cache-dir -r docker/requirements.txt jupyter-book --upgrade 


      - name: Build the book
        run: 
          jupyter-book build .

      - name: Upload book
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.PUBLISH_DIR }}
          retention-days: 7

  # Single deploy job since we're just deploying
  deploy:
      needs: build-book
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/dokken/jupyterbook'

      steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Setup Pages
          uses: actions/configure-pages@v2
    
        
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v1

